### ISSUE TITLE
Move `docs` and `integration-tests` modules to profiles

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkiverse-devops#269]
Because the `docs` and the `integration-tests` modules do not publish any Javadoc artifact (and the resulting JAR doesn't contain any binaries), it doesn't meet the requirements to be deployed in Maven Central.

See [central.sonatype.org/publish/requirements#supply-javadoc-and-sources](https://central.sonatype.org/publish/requirements/#supply-javadoc-and-sources) for more info

- Follow-up to https://github.com/quarkusio/quarkus/pull/43055

**Comment by gastaldi** [comment]
Created patches with the following command:

	./patch.sh -b move_docs_module -t "Avoid publishing support modules in Maven Central" -m "- As requested in https://github.com/quarkiverse/quarkiverse-devops/issues/269" -j /Users/ggastald/workspace/quarkiverse/quarkiverse-devops/patches/MoveModulesToProfiles.java

**Comment by ppalaga** [comment]
@gastaldi as I already [mentioned before](https://github.com/quarkiverse/quarkus-cxf/pull/1499#pullrequestreview-2292297788) the test modules need to get published to Central for all Platform members. See also https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/Quarkus.20Platform.20local.20build.20fails
