### ISSUE TITLE
Prevent users to report security issues via GitHub issues

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkiverse-devops#285]
We just got a security issue reported for QCXF (not linking it here intentionally). 

Quarkus has this warning in the [new issue form](https://github.com/quarkusio/quarkus/issues/new?template=bug_report.yml):

![image](https://github.com/user-attachments/assets/2642b832-d2f4-4bfb-a303-7a77f62a2de7)

I wonder whether we could adopt similar measures for Quarkiverse projects too?

There is also this [Privately reporting a security vulnerability](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability) feature of GitHUb that we perhaps might consider enabling?

**Comment by gastaldi** [comment]
> There is also this [Privately reporting a security vulnerability](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability) feature of GitHUb that we perhaps might consider enabling?

That requires https://github.com/integrations/terraform-provider-github/issues/2399 to be implemented. For now we can enable them individually in a manual basis.

**Comment by ppalaga** [comment]
> For now we can enable them individually in a manual basis.

Could you please enable it for Quarkus CXF?

**Comment by gastaldi** [comment]
> > For now we can enable them individually in a manual basis.
> 
> Could you please enable it for Quarkus CXF?
Of course, done.

**Comment by gastaldi** [comment]
I've enabled that by default in the Organization settings (https://github.com/organizations/quarkiverse/settings/security_products). It's now enabled in all Quarkiverse repositories.
